version: '3.3'
services:
  adminer:
    image: adminer:latest
    ports:
      - 9082:8080
    networks:
      - apiblog
  postgres:
    image: postgres:16
    volumes:
      - data-volume:/data/db
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - apiblog
networks:
  apiblog:
volumes:
  data-volume: